# Form implementation generated from reading ui file 'AdminDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_admindlg(object):
    def setupUi(self, admindlg):
        admindlg.setObjectName("admindlg")
        admindlg.resize(428, 351)
        self.verticalLayout = QtWidgets.QVBoxLayout(admindlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=admindlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.selectSurveyBtn = QtWidgets.QPushButton(parent=admindlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.selectSurveyBtn.setFont(font)
        self.selectSurveyBtn.setObjectName("selectSurveyBtn")
        self.verticalLayout_3.addWidget(self.selectSurveyBtn)
        self.createSurveyBtn = QtWidgets.QPushButton(parent=admindlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.createSurveyBtn.setFont(font)
        self.createSurveyBtn.setObjectName("createSurveyBtn")
        self.verticalLayout_3.addWidget(self.createSurveyBtn)
        self.setUpBtn = QtWidgets.QPushButton(parent=admindlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setUpBtn.setFont(font)
        self.setUpBtn.setObjectName("setUpBtn")
        self.verticalLayout_3.addWidget(self.setUpBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.doneBtn = QtWidgets.QPushButton(parent=admindlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.verticalLayout_3.addWidget(self.doneBtn)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(admindlg)
        QtCore.QMetaObject.connectSlotsByName(admindlg)

    def retranslateUi(self, admindlg):
        _translate = QtCore.QCoreApplication.translate
        admindlg.setWindowTitle(_translate("admindlg", "CLAMS Administration"))
        self.label.setText(_translate("admindlg", "CLAMS Administration"))
        self.selectSurveyBtn.setText(_translate("admindlg", "Change Active Survey"))
        self.createSurveyBtn.setText(_translate("admindlg", "Create Survey"))
        self.setUpBtn.setText(_translate("admindlg", "Edit and Setup"))
        self.doneBtn.setText(_translate("admindlg", "Done"))
