# Form implementation generated from reading ui file 'BasketEditDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_basketeditDlg(object):
    def setupUi(self, basketeditDlg):
        basketeditDlg.setObjectName("basketeditDlg")
        basketeditDlg.resize(534, 236)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(basketeditDlg)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(basketeditDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.editBasket = QtWidgets.QTableWidget(basketeditDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editBasket.setFont(font)
        self.editBasket.setObjectName("editBasket")
        self.editBasket.setColumnCount(0)
        self.editBasket.setRowCount(0)
        self.gridLayout.addWidget(self.editBasket, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelBtn = QtWidgets.QPushButton(basketeditDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setMinimumSize(QtCore.QSize(250, 58))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.okBtn = QtWidgets.QPushButton(basketeditDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okBtn.sizePolicy().hasHeightForWidth())
        self.okBtn.setSizePolicy(sizePolicy)
        self.okBtn.setMinimumSize(QtCore.QSize(250, 58))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(basketeditDlg)
        QtCore.QMetaObject.connectSlotsByName(basketeditDlg)

    def retranslateUi(self, basketeditDlg):
        _translate = QtCore.QCoreApplication.translate
        basketeditDlg.setWindowTitle(_translate("basketeditDlg", "Edit"))
        self.label.setText(_translate("basketeditDlg", "Select field to edit ..."))
        self.cancelBtn.setText(_translate("basketeditDlg", "Cancel"))
        self.okBtn.setText(_translate("basketeditDlg", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    basketeditDlg = QtWidgets.QDialog()
    ui = Ui_basketeditDlg()
    ui.setupUi(basketeditDlg)
    basketeditDlg.show()
    sys.exit(app.exec())
