# Form implementation generated from reading ui file 'C:\CLAMS_WPy64-31260_Deploy\CLAMS\ui\CPSSpecPlots.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(929, 679)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(580, 630, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.LWPlot = PlotWidget(parent=Dialog)
        self.LWPlot.setGeometry(QtCore.QRect(10, 170, 431, 331))
        self.LWPlot.setObjectName("LWPlot")
        self.OtoLengthPlot = PlotWidget(parent=Dialog)
        self.OtoLengthPlot.setGeometry(QtCore.QRect(480, 170, 431, 331))
        self.OtoLengthPlot.setObjectName("OtoLengthPlot")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
from pyqtgraph import PlotWidget
