# Form implementation generated from reading ui file 'DevicesConfigDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DevicesConfigDlg(object):
    def setupUi(self, DevicesConfigDlg):
        DevicesConfigDlg.setObjectName("DevicesConfigDlg")
        DevicesConfigDlg.resize(552, 637)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=DevicesConfigDlg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 511, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deviceConfigTable = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        self.deviceConfigTable.setFont(font)
        self.deviceConfigTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.deviceConfigTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.deviceConfigTable.setObjectName("deviceConfigTable")
        self.deviceConfigTable.setColumnCount(3)
        self.deviceConfigTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.deviceConfigTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.deviceConfigTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.deviceConfigTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.deviceConfigTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout.addWidget(self.addBtn)
        self.editBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.editBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout.addWidget(self.editBtn)
        self.doneBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.horizontalLayout.addWidget(self.doneBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DevicesConfigDlg)
        QtCore.QMetaObject.connectSlotsByName(DevicesConfigDlg)

    def retranslateUi(self, DevicesConfigDlg):
        _translate = QtCore.QCoreApplication.translate
        DevicesConfigDlg.setWindowTitle(_translate("DevicesConfigDlg", "Dialog"))
        self.deviceConfigTable.setSortingEnabled(True)
        item = self.deviceConfigTable.horizontalHeaderItem(0)
        item.setText(_translate("DevicesConfigDlg", "Id"))
        item = self.deviceConfigTable.horizontalHeaderItem(1)
        item.setText(_translate("DevicesConfigDlg", "Parameter"))
        item = self.deviceConfigTable.horizontalHeaderItem(2)
        item.setText(_translate("DevicesConfigDlg", "Value"))
        self.addBtn.setText(_translate("DevicesConfigDlg", "Add"))
        self.editBtn.setText(_translate("DevicesConfigDlg", "Edit"))
        self.doneBtn.setText(_translate("DevicesConfigDlg", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DevicesConfigDlg = QtWidgets.QDialog()
    ui = Ui_DevicesConfigDlg()
    ui.setupUi(DevicesConfigDlg)
    DevicesConfigDlg.show()
    sys.exit(app.exec())
