# Form implementation generated from reading ui file 'DeleteDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_deleteDlg(object):
    def setupUi(self, deleteDlg):
        deleteDlg.setObjectName("deleteDlg")
        deleteDlg.resize(382, 275)
        self.verticalLayout = QtWidgets.QVBoxLayout(deleteDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=deleteDlg)
        self.label.setMaximumSize(QtCore.QSize(16777215, 112))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.deleteItems = QtWidgets.QComboBox(parent=deleteDlg)
        self.deleteItems.setObjectName("deleteItems")
        self.gridLayout.addWidget(self.deleteItems, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelBtn = QtWidgets.QPushButton(parent=deleteDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Croatian, QtCore.QLocale.Country.Croatia))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.okayBtn = QtWidgets.QPushButton(parent=deleteDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.okayBtn.setFont(font)
        self.okayBtn.setObjectName("okayBtn")
        self.horizontalLayout.addWidget(self.okayBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(deleteDlg)
        QtCore.QMetaObject.connectSlotsByName(deleteDlg)

    def retranslateUi(self, deleteDlg):
        _translate = QtCore.QCoreApplication.translate
        deleteDlg.setWindowTitle(_translate("deleteDlg", "Ack.. A Question..."))
        self.label.setText(_translate("deleteDlg", "Delete:"))
        self.cancelBtn.setText(_translate("deleteDlg", "Cancel"))
        self.okayBtn.setText(_translate("deleteDlg", "Okay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteDlg = QtWidgets.QDialog()
    ui = Ui_deleteDlg()
    ui.setupUi(deleteDlg)
    deleteDlg.show()
    sys.exit(app.exec())
