# Form implementation generated from reading ui file 'EditPersonnelDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditPersonnelDlg(object):
    def setupUi(self, EditPersonnelDlg):
        EditPersonnelDlg.setObjectName("EditPersonnelDlg")
        EditPersonnelDlg.resize(413, 262)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=EditPersonnelDlg)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 371, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.affiliationLabel = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.affiliationLabel.setObjectName("affiliationLabel")
        self.gridLayout.addWidget(self.affiliationLabel, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.isActive = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.isActive.setText("")
        self.isActive.setObjectName("isActive")
        self.gridLayout.addWidget(self.isActive, 2, 1, 1, 1)
        self.scientistLabel = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.scientistLabel.setObjectName("scientistLabel")
        self.gridLayout.addWidget(self.scientistLabel, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=EditPersonnelDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 190, 301, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        self.editBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout_2.addWidget(self.editBtn)

        self.retranslateUi(EditPersonnelDlg)
        QtCore.QMetaObject.connectSlotsByName(EditPersonnelDlg)

    def retranslateUi(self, EditPersonnelDlg):
        _translate = QtCore.QCoreApplication.translate
        EditPersonnelDlg.setWindowTitle(_translate("EditPersonnelDlg", "Dialog"))
        self.label_2.setText(_translate("EditPersonnelDlg", "Affiliation"))
        self.label_3.setText(_translate("EditPersonnelDlg", "Active"))
        self.label.setText(_translate("EditPersonnelDlg", "Scientist"))
        self.cancelBtn.setText(_translate("EditPersonnelDlg", "Cancel"))
        self.editBtn.setText(_translate("EditPersonnelDlg", "Add Personnel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditPersonnelDlg = QtWidgets.QDialog()
    ui = Ui_EditPersonnelDlg()
    ui.setupUi(EditPersonnelDlg)
    EditPersonnelDlg.show()
    sys.exit(app.exec())
