# Form implementation generated from reading ui file 'EditSpeciesDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditSpeciesDlg(object):
    def setupUi(self, EditSpeciesDlg):
        EditSpeciesDlg.setObjectName("EditSpeciesDlg")
        EditSpeciesDlg.resize(490, 336)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=EditSpeciesDlg)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 431, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.parentTaxon = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.parentTaxon.setFont(font)
        self.parentTaxon.setObjectName("parentTaxon")
        self.gridLayout.addWidget(self.parentTaxon, 0, 1, 1, 1)
        self.sciNameLabel = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.sciNameLabel.setObjectName("sciNameLabel")
        self.gridLayout.addWidget(self.sciNameLabel, 2, 1, 1, 1)
        self.commonNameLabel = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.commonNameLabel.setObjectName("commonNameLabel")
        self.gridLayout.addWidget(self.commonNameLabel, 3, 1, 1, 1)
        self.speciesCodeLabel = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.speciesCodeLabel.setObjectName("speciesCodeLabel")
        self.gridLayout.addWidget(self.speciesCodeLabel, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=EditSpeciesDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 250, 313, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        self.editBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout_2.addWidget(self.editBtn)

        self.retranslateUi(EditSpeciesDlg)
        QtCore.QMetaObject.connectSlotsByName(EditSpeciesDlg)

    def retranslateUi(self, EditSpeciesDlg):
        _translate = QtCore.QCoreApplication.translate
        EditSpeciesDlg.setWindowTitle(_translate("EditSpeciesDlg", "Dialog"))
        self.label_3.setText(_translate("EditSpeciesDlg", "Scientific Name"))
        self.label_4.setText(_translate("EditSpeciesDlg", "Common Name"))
        self.parentTaxon.setText(_translate("EditSpeciesDlg", "161,061"))
        self.label_2.setText(_translate("EditSpeciesDlg", "Parent Taxon"))
        self.label.setText(_translate("EditSpeciesDlg", "Species Code"))
        self.cancelBtn.setText(_translate("EditSpeciesDlg", "Cancel"))
        self.editBtn.setText(_translate("EditSpeciesDlg", "Add Species"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditSpeciesDlg = QtWidgets.QDialog()
    ui = Ui_EditSpeciesDlg()
    ui.setupUi(EditSpeciesDlg)
    EditSpeciesDlg.show()
    sys.exit(app.exec())
