# Form implementation generated from reading ui file 'EditDeviceConfig.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditDeviceConfig(object):
    def setupUi(self, EditDeviceConfig):
        EditDeviceConfig.setObjectName("EditDeviceConfig")
        EditDeviceConfig.resize(490, 278)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=EditDeviceConfig)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 431, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.paramValLabel = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.paramValLabel.setObjectName("paramValLabel")
        self.gridLayout.addWidget(self.paramValLabel, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.deviceParamsCB = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.deviceParamsCB.setObjectName("deviceParamsCB")
        self.gridLayout.addWidget(self.deviceParamsCB, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.deviceIdLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.deviceIdLabel.setFont(font)
        self.deviceIdLabel.setText("")
        self.deviceIdLabel.setObjectName("deviceIdLabel")
        self.gridLayout.addWidget(self.deviceIdLabel, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=EditDeviceConfig)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 190, 313, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        self.editBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout_2.addWidget(self.editBtn)

        self.retranslateUi(EditDeviceConfig)
        QtCore.QMetaObject.connectSlotsByName(EditDeviceConfig)

    def retranslateUi(self, EditDeviceConfig):
        _translate = QtCore.QCoreApplication.translate
        EditDeviceConfig.setWindowTitle(_translate("EditDeviceConfig", "Dialog"))
        self.label_3.setText(_translate("EditDeviceConfig", "Parameter Value"))
        self.label_2.setText(_translate("EditDeviceConfig", "Device Parameter"))
        self.label.setText(_translate("EditDeviceConfig", "Device Id"))
        self.cancelBtn.setText(_translate("EditDeviceConfig", "Cancel"))
        self.editBtn.setText(_translate("EditDeviceConfig", "Add Measurement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditDeviceConfig = QtWidgets.QDialog()
    ui = Ui_EditDeviceConfig()
    ui.setupUi(EditDeviceConfig)
    EditDeviceConfig.show()
    sys.exit(app.exec())
