# Form implementation generated from reading ui file 'EditMeasurement.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditMeasurement(object):
    def setupUi(self, EditMeasurement):
        EditMeasurement.setObjectName("EditMeasurement")
        EditMeasurement.resize(490, 278)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=EditMeasurement)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 431, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.moduleCB = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.moduleCB.setObjectName("moduleCB")
        self.gridLayout.addWidget(self.moduleCB, 2, 1, 1, 1)
        self.deviceCB = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.deviceCB.setObjectName("deviceCB")
        self.gridLayout.addWidget(self.deviceCB, 1, 1, 1, 1)
        self.measurementCB = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.measurementCB.setObjectName("measurementCB")
        self.gridLayout.addWidget(self.measurementCB, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=EditMeasurement)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 190, 313, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        self.editBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout_2.addWidget(self.editBtn)

        self.retranslateUi(EditMeasurement)
        QtCore.QMetaObject.connectSlotsByName(EditMeasurement)

    def retranslateUi(self, EditMeasurement):
        _translate = QtCore.QCoreApplication.translate
        EditMeasurement.setWindowTitle(_translate("EditMeasurement", "Dialog"))
        self.label_2.setText(_translate("EditMeasurement", "Device Id"))
        self.label.setText(_translate("EditMeasurement", "Measurement"))
        self.label_3.setText(_translate("EditMeasurement", "Module"))
        self.cancelBtn.setText(_translate("EditMeasurement", "Cancel"))
        self.editBtn.setText(_translate("EditMeasurement", "Add Measurement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditMeasurement = QtWidgets.QDialog()
    ui = Ui_EditMeasurement()
    ui.setupUi(EditMeasurement)
    EditMeasurement.show()
    sys.exit(app.exec())
