# Form implementation generated from reading ui file 'MeasurementsDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MeasurementsDlg(object):
    def setupUi(self, MeasurementsDlg):
        MeasurementsDlg.setObjectName("MeasurementsDlg")
        MeasurementsDlg.resize(552, 637)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=MeasurementsDlg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 511, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.measurementTable = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        self.measurementTable.setFont(font)
        self.measurementTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.measurementTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.measurementTable.setObjectName("measurementTable")
        self.measurementTable.setColumnCount(4)
        self.measurementTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.measurementTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.measurementTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.measurementTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.measurementTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.measurementTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout.addWidget(self.addBtn)
        self.editBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.editBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout.addWidget(self.editBtn)
        self.doneBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.horizontalLayout.addWidget(self.doneBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MeasurementsDlg)
        QtCore.QMetaObject.connectSlotsByName(MeasurementsDlg)

    def retranslateUi(self, MeasurementsDlg):
        _translate = QtCore.QCoreApplication.translate
        MeasurementsDlg.setWindowTitle(_translate("MeasurementsDlg", "Dialog"))
        self.measurementTable.setSortingEnabled(True)
        item = self.measurementTable.horizontalHeaderItem(0)
        item.setText(_translate("MeasurementsDlg", "Id"))
        item = self.measurementTable.horizontalHeaderItem(1)
        item.setText(_translate("MeasurementsDlg", "Measurement Type"))
        item = self.measurementTable.horizontalHeaderItem(2)
        item.setText(_translate("MeasurementsDlg", "Device Id"))
        item = self.measurementTable.horizontalHeaderItem(3)
        item.setText(_translate("MeasurementsDlg", "Module"))
        self.addBtn.setText(_translate("MeasurementsDlg", "Add"))
        self.editBtn.setText(_translate("MeasurementsDlg", "Edit"))
        self.doneBtn.setText(_translate("MeasurementsDlg", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MeasurementsDlg = QtWidgets.QDialog()
    ui = Ui_MeasurementsDlg()
    ui.setupUi(MeasurementsDlg)
    MeasurementsDlg.show()
    sys.exit(app.exec())
