# Form implementation generated from reading ui file 'C:\CLAMS_WPy64-31260_Deploy\CLAMS\ui\SampleTypeSelDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SampleTypeSelDlg(object):
    def setupUi(self, SampleTypeSelDlg):
        SampleTypeSelDlg.setObjectName("SampleTypeSelDlg")
        SampleTypeSelDlg.resize(378, 250)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SampleTypeSelDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=SampleTypeSelDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.speciesBtn = QtWidgets.QPushButton(parent=SampleTypeSelDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesBtn.sizePolicy().hasHeightForWidth())
        self.speciesBtn.setSizePolicy(sizePolicy)
        self.speciesBtn.setMinimumSize(QtCore.QSize(165, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.speciesBtn.setFont(font)
        self.speciesBtn.setObjectName("speciesBtn")
        self.verticalLayout.addWidget(self.speciesBtn)
        self.presentBtn = QtWidgets.QPushButton(parent=SampleTypeSelDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presentBtn.sizePolicy().hasHeightForWidth())
        self.presentBtn.setSizePolicy(sizePolicy)
        self.presentBtn.setMinimumSize(QtCore.QSize(165, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.presentBtn.setFont(font)
        self.presentBtn.setObjectName("presentBtn")
        self.verticalLayout.addWidget(self.presentBtn)
        self.noExtrapBtn = QtWidgets.QPushButton(parent=SampleTypeSelDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noExtrapBtn.sizePolicy().hasHeightForWidth())
        self.noExtrapBtn.setSizePolicy(sizePolicy)
        self.noExtrapBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setItalic(False)
        self.noExtrapBtn.setFont(font)
        self.noExtrapBtn.setObjectName("noExtrapBtn")
        self.verticalLayout.addWidget(self.noExtrapBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SampleTypeSelDlg)
        QtCore.QMetaObject.connectSlotsByName(SampleTypeSelDlg)

    def retranslateUi(self, SampleTypeSelDlg):
        _translate = QtCore.QCoreApplication.translate
        SampleTypeSelDlg.setWindowTitle(_translate("SampleTypeSelDlg", "Set Sample Type"))
        self.label.setText(_translate("SampleTypeSelDlg", "Select the Sample Type"))
        self.speciesBtn.setText(_translate("SampleTypeSelDlg", "Species"))
        self.presentBtn.setText(_translate("SampleTypeSelDlg", "Present"))
        self.noExtrapBtn.setText(_translate("SampleTypeSelDlg", "NoExtrapolation"))
