# Form implementation generated from reading ui file 'SpeciesEditDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_speciesEditDlg(object):
    def setupUi(self, speciesEditDlg):
        speciesEditDlg.setObjectName("speciesEditDlg")
        speciesEditDlg.resize(539, 225)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(speciesEditDlg)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=speciesEditDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelBtn = QtWidgets.QPushButton(parent=speciesEditDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setMinimumSize(QtCore.QSize(250, 58))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.okBtn = QtWidgets.QPushButton(parent=speciesEditDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okBtn.sizePolicy().hasHeightForWidth())
        self.okBtn.setSizePolicy(sizePolicy)
        self.okBtn.setMinimumSize(QtCore.QSize(250, 58))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.editSpecies = QtWidgets.QTableWidget(parent=speciesEditDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editSpecies.setFont(font)
        self.editSpecies.setObjectName("editSpecies")
        self.editSpecies.setColumnCount(0)
        self.editSpecies.setRowCount(0)
        self.gridLayout.addWidget(self.editSpecies, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(speciesEditDlg)
        QtCore.QMetaObject.connectSlotsByName(speciesEditDlg)

    def retranslateUi(self, speciesEditDlg):
        _translate = QtCore.QCoreApplication.translate
        speciesEditDlg.setWindowTitle(_translate("speciesEditDlg", "Edit Species"))
        self.label.setText(_translate("speciesEditDlg", "Select field to edit ..."))
        self.cancelBtn.setText(_translate("speciesEditDlg", "Cancel"))
        self.okBtn.setText(_translate("speciesEditDlg", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    speciesEditDlg = QtWidgets.QDialog()
    ui = Ui_speciesEditDlg()
    ui.setupUi(speciesEditDlg)
    speciesEditDlg.show()
    sys.exit(app.exec())
