# Form implementation generated from reading ui file 'SetupDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SetupDlg(object):
    def setupUi(self, SetupDlg):
        SetupDlg.setObjectName("SetupDlg")
        SetupDlg.resize(399, 520)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=SetupDlg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.editPersonBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.editPersonBtn.setFont(font)
        self.editPersonBtn.setObjectName("editPersonBtn")
        self.verticalLayout.addWidget(self.editPersonBtn)
        self.editWorkstationBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.editWorkstationBtn.setFont(font)
        self.editWorkstationBtn.setObjectName("editWorkstationBtn")
        self.verticalLayout.addWidget(self.editWorkstationBtn)
        self.editDevicesBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setUnderline(False)
        self.editDevicesBtn.setFont(font)
        self.editDevicesBtn.setObjectName("editDevicesBtn")
        self.verticalLayout.addWidget(self.editDevicesBtn)
        self.editSpeciesBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setUnderline(False)
        self.editSpeciesBtn.setFont(font)
        self.editSpeciesBtn.setObjectName("editSpeciesBtn")
        self.verticalLayout.addWidget(self.editSpeciesBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.doneBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.verticalLayout.addWidget(self.doneBtn)

        self.retranslateUi(SetupDlg)
        QtCore.QMetaObject.connectSlotsByName(SetupDlg)

    def retranslateUi(self, SetupDlg):
        _translate = QtCore.QCoreApplication.translate
        SetupDlg.setWindowTitle(_translate("SetupDlg", "Dialog"))
        self.label.setText(_translate("SetupDlg", "Edit and Setup"))
        self.editPersonBtn.setText(_translate("SetupDlg", "Edit Personnel"))
        self.editWorkstationBtn.setText(_translate("SetupDlg", "Edit Workstation"))
        self.editDevicesBtn.setText(_translate("SetupDlg", "Edit Devices"))
        self.editSpeciesBtn.setText(_translate("SetupDlg", "Edit Species"))
        self.doneBtn.setText(_translate("SetupDlg", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SetupDlg = QtWidgets.QDialog()
    ui = Ui_SetupDlg()
    ui.setupUi(SetupDlg)
    SetupDlg.show()
    sys.exit(app.exec())
