# Form implementation generated from reading ui file 'SpeciesDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SpeciesDlg(object):
    def setupUi(self, SpeciesDlg):
        SpeciesDlg.setObjectName("SpeciesDlg")
        SpeciesDlg.resize(552, 637)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=SpeciesDlg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 511, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.speciesTable = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        self.speciesTable.setFont(font)
        self.speciesTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.speciesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.speciesTable.setObjectName("speciesTable")
        self.speciesTable.setColumnCount(4)
        self.speciesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.speciesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.speciesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.speciesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.speciesTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.speciesTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout.addWidget(self.addBtn)
        self.doneBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.horizontalLayout.addWidget(self.doneBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SpeciesDlg)
        QtCore.QMetaObject.connectSlotsByName(SpeciesDlg)

    def retranslateUi(self, SpeciesDlg):
        _translate = QtCore.QCoreApplication.translate
        SpeciesDlg.setWindowTitle(_translate("SpeciesDlg", "Dialog"))
        self.speciesTable.setSortingEnabled(True)
        item = self.speciesTable.horizontalHeaderItem(0)
        item.setText(_translate("SpeciesDlg", "Species Code"))
        item = self.speciesTable.horizontalHeaderItem(1)
        item.setText(_translate("SpeciesDlg", "Parent Taxon"))
        item = self.speciesTable.horizontalHeaderItem(2)
        item.setText(_translate("SpeciesDlg", "Scientific Name"))
        item = self.speciesTable.horizontalHeaderItem(3)
        item.setText(_translate("SpeciesDlg", "Common Name"))
        self.addBtn.setText(_translate("SpeciesDlg", "Add"))
        self.doneBtn.setText(_translate("SpeciesDlg", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpeciesDlg = QtWidgets.QDialog()
    ui = Ui_SpeciesDlg()
    ui.setupUi(SpeciesDlg)
    SpeciesDlg.show()
    sys.exit(app.exec())
